// <auto-generated />
namespace SeraySis.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class kodekle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kodekle));
        
        string IMigrationMetadata.Id
        {
            get { return "201802211056146_kod-ekle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
