// <auto-generated />
namespace SeraySis.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class stokkartidduzelt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stokkartidduzelt));
        
        string IMigrationMetadata.Id
        {
            get { return "201802191353080_stokkart-id-duzelt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
